# Maximum supported render distance. Clients will be capped to this value.
# Required.
render_distance: 128

# TODO
distant_generation_enabled: true

# TODO
full_data_request_concurrency_limit: 20

# TODO
real_time_updates_enabled: true

# TODO
login_data_sync_enabled: true

# TODO
login_data_sync_rc_limit: 50
